### ISSUE TITLE
Problème de génération de certains PDF

### ISSUE THREAD

**Issue by jldeochandiano** [edinum/pdfgen#3]
Bonjour,
Le générateur de PDF est activé sur une revue de la plateforme Prairial. Le générateur fonctionne généralement bien. Mais deux PDF qui ont été imparfaitement générés :
•	https://publications-prairial.fr/pratiques-et-formes-litteraires/index.php?id=221
•	https://publications-prairial.fr/pratiques-et-formes-litteraires/index.php?id=201
La totalité des PDF n’a pas été générée. Il semblerait que des illustrations de grande taille ont posé problème et que le processus s’est arrêté en cours de route, mais tout en produisant un PDF valide. 

Merci d'avance pour votre aide.
Jean-Luc de Ochandiano
Université Jean-Moulin Lyon 3

**Comment by brrd** [comment]
Malheureusement c'est un problème connu de Paged.js, qui est encore en phase active de développement. Plusieurs problèmes de ce type sont signalés dans les issues de Paged.js (https://gitlab.pagedmedia.org/tools/pagedjs) et des solutions semblent en cours d'élaboration. Il faudra donc surveiller ça, et mettre à jour la bibliothèque lorsque les prochaines versions seront disponibles, en espérant qu'un correctif arrive rapidement.

Je vais étudier les solutions de contournement disponibles mais cela ne sera probablement pas idéal.

**Comment by brrd** [comment]
@jldeochandiano Pourriez-vous nous envoyer des documents source d'articles qui posent problème ? Par exemple : https://publications-prairial.fr/pratiques-et-formes-litteraires/index.php?id=225

**Comment by brrd** [comment]
Après plusieurs tests il apparait que ces erreurs proviennent d'un plantage de Paged.js lorsqu'il met en page des éléments (principalement des images et des tableaux) dont la hauteur excède la taille de la page.

Je viens de publier une version 1.0.1 qui limite la hauteur des images à 50% de la page. Il me semble que cela permettra de régler un grand nombre de problèmes. 

Je marque ce ticket comme résolu mais il n'est pas impossible que d'autres problèmes apparaissent dans d'autres situations. Le cas échéant @jldeochandiano n'hésitez pas à rouvrir ce ticket en mentionnant l'URL de l'article problématique et en joignant le document source.

**Comment by jldeochandiano** [comment]
Re-bonjour,

Merci beaucoup pour la modification réalisée qui devrait permettre de résoudre le problème rencontré. Nous allons installer le patch et faire des tests sur les pdf qui bloquaient.

Bien cordialement

Jean-Luc de Ochandiano
------------------------------------------------------
Responsable du Service de soutien aux revues scientifiques en SHS
Responsable de Prairial<https://publications-prairial.fr/accueil/>, plateforme de revues en accès ouvert
Bibliothèques universitaires
Université Jean Moulin Lyon 3

ADRESSE GÉOGRAPHIQUE > Manufacture des Tabacs | 6 cours Albert Thomas | LYON 8e
ADRESSE POSTALE > Bibliothèque de la Manufacture | 1C avenue des Frères Lumière | CS 78242 - 69372 LYON CEDEX 08
Ligne directe : +33 (0)4 78 78 79 07

http://bu.univ-lyon3.fr<http://bu.univ-lyon3.fr/> | Suivez-nous > Facebook<https://www.facebook.com/bulyon3/> | Twitter<https://twitter.com/bulyon3> | Instagram<https://www.instagram.com/bu.lyon3/?hl=fr>
---------------------------------------------------
L'Université Jean Moulin est membre fondateur de l'Université de Lyon

De : Thomas Brouard ***@***.***>
Envoyé : vendredi 4 juin 2021 16:21
À : edinum/pdfgen ***@***.***>
Cc : DE OCHANDIANO Jean-Luc ***@***.***>; Mention ***@***.***>
Objet : Re: [edinum/pdfgen] Problème de génération de certains PDF (#3)


Après plusieurs tests il apparait que ces erreurs proviennent d'un plantage de Paged.js lorsqu'il met en page des éléments (principalement des images et des tableaux) dont la hauteur excède la taille de la page.

Je viens de publier une version 1.0.1 qui limite la hauteur des images à 50% de la page. Il me semble que cela permettra de régler un grand nombre de problèmes.

Je marque ce ticket comme résolu mais il n'est pas impossible que d'autres problèmes apparaissent dans d'autres situations. Le cas échéant @jldeochandiano<https://github.com/jldeochandiano> n'hésitez pas à rouvrir ce ticket en mentionnant l'URL de l'article problématique et en joignant le document source.
