### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by ssonnet** [edinum/pdfgen#6]
Bonjour,
J'essaye de faire fonctionner votre plugin qui me renvoie une erreur 404 lorsque je demande la génération du PDF (la prévisualisation avec ?do=_pdfgen_view fonctionne). Lodel est installé sur une VM locale (virtualbox) et le système de conversion sur mon instance Docker Desktop (windows). Je vous mets le message d'erreur ci-dessous. Auriez-vous une idée du problème ?
Cordialement.

#0  LodelException::exception_handler(TheCodingMachine\Gotenberg\ClientException Object ([*message] => Not Found,[Exceptionstring] => ,[*code] => 404,[*file] => /var/www/html/lodel/share/plugins/custom/pdfgen/vendor/thecodingmachine/gotenberg-php-client/src/Client.php,[*line] => 106,[Exceptiontrace] => Array ([0] => Array ([file] => /var/www/html/lodel/share/plugins/custom/pdfgen/vendor/thecodingmachine/gotenberg-php-client/src/Client.php,[line] => 57,[function] => handleResponse,[class] => TheCodingMachine\Gotenberg\Client,[type] => ->,[args] => Array ([0] => GuzzleHttp\Psr7\Response Object ([GuzzleHttp\Psr7\ResponsereasonPhrase] => Not Found,[GuzzleHttp\Psr7\ResponsestatusCode] => 404,[GuzzleHttp\Psr7\Responseheaders] => Array ([Content-Length] => Array ([0] => 9),[Content-Type] => Array ([0] => text/plain; charset=UTF-8),[Date] => Array ([0] => Thu, 28 Oct 2021 10:01:01 GMT),[Gotenberg-Trace] => Array ([0] => da10a4c3-d5ae-4081-8d45-55824cf375e3)),[GuzzleHttp\Psr7\ResponseheaderNames] => Array ([content-length] => Content-Length,[content-type] => Content-Type,[date] => Date,[gotenberg-trace] => Gotenberg-Trace),[GuzzleHttp\Psr7\Responseprotocol] => 1.1,[GuzzleHttp\Psr7\Responsestream] => GuzzleHttp\Psr7\Stream Object ([GuzzleHttp\Psr7\Streamstream] => Resource id #56,[GuzzleHttp\Psr7\Streamsize] => ,[GuzzleHttp\Psr7\Streamseekable] => 1,[GuzzleHttp\Psr7\Streamreadable] => 1,[GuzzleHttp\Psr7\Streamwritable] => 1,[GuzzleHttp\Psr7\Streamuri] => php://temp,[GuzzleHttp\Psr7\StreamcustomMetadata] => Array ())))),[1] => Array ([file] => /var/www/html/lodel/share/plugins/custom/pdfgen/pdfgen.php,[line] => 68,[function] => store,[class] => TheCodingMachine\Gotenberg\Client,[type] => ->,[args] => Array ([0] => TheCodingMachine\Gotenberg\URLRequest Object ([TheCodingMachine\Gotenberg\URLRequestURL] => http://ara.local/lodel/sitenova/?do=_pdfgen_view&document=67&lang=fr&debug=,[TheCodingMachine\Gotenberg\ChromeRequestwaitDelay] => ,[TheCodingMachine\Gotenberg\ChromeRequestheader] => ,[TheCodingMachine\Gotenberg\ChromeRequestfooter] => ,[TheCodingMachine\Gotenberg\ChromeRequestpaperWidth] => 8.27,[TheCodingMachine\Gotenberg\ChromeRequestpaperHeight] => 11.7,[TheCodingMachine\Gotenberg\ChromeRequestmarginTop] => 0,[TheCodingMachine\Gotenberg\ChromeRequestmarginBottom] => 0,[TheCodingMachine\Gotenberg\ChromeRequestmarginLeft] => 0,[TheCodingMachine\Gotenberg\ChromeRequestmarginRight] => 0,[TheCodingMachine\Gotenberg\ChromeRequestlandscape] => ,[TheCodingMachine\Gotenberg\ChromeRequestpageRanges] => ,[TheCodingMachine\Gotenberg\ChromeRequestgoogleChromeRpccBufferSize] => ,[TheCodingMachine\Gotenberg\ChromeRequestscale] => ,[TheCodingMachine\Gotenberg\RequestresultFilename] => ,[TheCodingMachine\Gotenberg\RequestwaitTimeout] => ,[TheCodingMachine\Gotenberg\RequestwebhookURL] => ,[TheCodingMachine\Gotenberg\RequestwebhookURLTimeout] => ,[*customHTTPHeaders] => Array ()),[1] => /var/www/html/lodel/sitenova/CACHE/e71411a00aec7a755a33c6dc3f8547e9)),[2] => Array ([file] => /var/www/html/lodel/lodel/scripts/logic/class.mainplugins.php,[line] => 90,[function] => getAction,[class] => pdfgen,[type] => ->,[args] => Array ([0] => Array ([do] => pdfgen_get,[document] => 67,[lang] => fr,[id] => 0,[idgroup] => 0,[idclass] => 0,[idparent] => 0,[idtype] => 0,[identity] => 0,[version] => 1.0,[shareurl] => /lodel/share,[extensionscripts] => php,[currenturl] => http://ara.local/lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr,[siteroot] => ,[sharedir] => .././share,[tableprefix] => ,[tp] => ,[base_rep] => Array (),[charset] => utf-8,[site] => sitenova,[db_charset] => utf8mb4,[siteinfos] => Array ([id] => 1,[title] => Site Nova,[subtitle] => ,[name] => sitenova,[path] => /sitenova,[url] => http://ara.local/lodel/sitenova,[langdef] => ,[lang] => ,[status] => 1,[upd] => 2021-10-27 14:38:13),[siteurl] => http://ara.local/lodel/sitenova,[options] => Array ([metadonneessite] => Array ([titresite] => Titresite,[soustitresite] => ,[titresiteabrege] => Titre abrégé du site,[descriptionsite] => ,[urldusite] => ,[issn] => ,[issn_electronique] => ,[editeur] => ,[adresseediteur] => ,[producteursite] => ,[diffuseursite] => ,[droitsauteur] => ,[directeurpublication] => ,[redacteurenchef] => ,[courrielwebmaster] => ,[courrielabuse] => ,[motsclesdusite] => ,[langueprincipale] => fr,[typepublication] => Revue,[pdf] => ,[pdf_electronique] => ,[imagehabillee] => ),[diffusionelectronique] => Array ([bouquetfreemium] => ,[librairieelectronique] => ,[prixcommercialisationnumero] => ),[optionsaffichage] => Array ([affichageindexannuel] => ,[affichageindexparlangue] => ,[affichageindexcr] => ,[affichageindexpersonnes] => First name Surname,[barrenavaffichagenumero] => per issue,[affichageremerciements] => top,[pub_level_accordion] => none,[firstlogo] => ,[math] => ,[hide_varia] => ),[optionsgenerales] => Array ([emversion] => 1.0.2)),[sitelang] => fr,[defaultlang] => Array ([AR] => العربية,[BS] => Bosanski jezik,[CS] => Česky,[DE] => Deutsch,[EL] => Ελληνικά,[EN] => English,[ES] => Español,[ET] => Eesti keel,[EU] => Euskara,[FA] => ‫فارسی,[FI] => Suomen kieli,[FR] => Français,[GA] => Gaeilge,[HR] => Hrvatski,[HU] => Magyar,[IT] => Italiano,[HE] => ‫עברית,[JA] => 日本語,[KV] => коми кыв,[LA] => Latine,[LV] => Latviešu valoda,[MK] => македонски јазик,[NL] => Nederlands,[OC] => Occitan,[PL] => Polski,[PT] => Português,[RU] => Русский язык,[SL] => Slovenščina,[SR] => српски језик,[SV] => Svenska,[TR] => Türkçe,[ZH] => 中文),[installlang] => fr,[login] => ssonnet,[lodeluser] => Array ([rights] => 128,[lang] => fr,[id] => 2,[gui_complexity] => 64,[name] => ssonnet,[groups] => ,[desk] => 1,[restricted_user] => 1,[adminlodel] => 1,[admin] => 1,[editor] => 1,[redactor] => 1,[visitor] => 1,[idsession] => ,[session] => ),[clearcacheurl] => /lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr&amp;clearcache=oui,[lo] => plugins,[error] => Array (),[triggers] => Array ([0] => preview,[1] => postview,[2] => preedit,[3] => postedit,[4] => prelogin,[5] => postlogin,[6] => preauth,[7] => postauth)),[1] => Array ())),[3] => Array ([file] => /var/www/html/lodel/lodel/scripts/controller.php,[line] => 543,[function] => factory,[class] => MainPluginsLogic,[type] => ->,[args] => Array ([0] => Array ([do] => pdfgen_get,[document] => 67,[lang] => fr,[id] => 0,[idgroup] => 0,[idclass] => 0,[idparent] => 0,[idtype] => 0,[identity] => 0,[version] => 1.0,[shareurl] => /lodel/share,[extensionscripts] => php,[currenturl] => http://ara.local/lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr,[siteroot] => ,[sharedir] => .././share,[tableprefix] => ,[tp] => ,[base_rep] => Array (),[charset] => utf-8,[site] => sitenova,[db_charset] => utf8mb4,[siteinfos] => Array ([id] => 1,[title] => Site Nova,[subtitle] => ,[name] => sitenova,[path] => /sitenova,[url] => http://ara.local/lodel/sitenova,[langdef] => ,[lang] => ,[status] => 1,[upd] => 2021-10-27 14:38:13),[siteurl] => http://ara.local/lodel/sitenova,[options] => Array ([metadonneessite] => Array ([titresite] => Titresite,[soustitresite] => ,[titresiteabrege] => Titre abrégé du site,[descriptionsite] => ,[urldusite] => ,[issn] => ,[issn_electronique] => ,[editeur] => ,[adresseediteur] => ,[producteursite] => ,[diffuseursite] => ,[droitsauteur] => ,[directeurpublication] => ,[redacteurenchef] => ,[courrielwebmaster] => ,[courrielabuse] => ,[motsclesdusite] => ,[langueprincipale] => fr,[typepublication] => Revue,[pdf] => ,[pdf_electronique] => ,[imagehabillee] => ),[diffusionelectronique] => Array ([bouquetfreemium] => ,[librairieelectronique] => ,[prixcommercialisationnumero] => ),[optionsaffichage] => Array ([affichageindexannuel] => ,[affichageindexparlangue] => ,[affichageindexcr] => ,[affichageindexpersonnes] => First name Surname,[barrenavaffichagenumero] => per issue,[affichageremerciements] => top,[pub_level_accordion] => none,[firstlogo] => ,[math] => ,[hide_varia] => ),[optionsgenerales] => Array ([emversion] => 1.0.2)),[sitelang] => fr,[defaultlang] => Array ([AR] => العربية,[BS] => Bosanski jezik,[CS] => Česky,[DE] => Deutsch,[EL] => Ελληνικά,[EN] => English,[ES] => Español,[ET] => Eesti keel,[EU] => Euskara,[FA] => ‫فارسی,[FI] => Suomen kieli,[FR] => Français,[GA] => Gaeilge,[HR] => Hrvatski,[HU] => Magyar,[IT] => Italiano,[HE] => ‫עברית,[JA] => 日本語,[KV] => коми кыв,[LA] => Latine,[LV] => Latviešu valoda,[MK] => македонски јазик,[NL] => Nederlands,[OC] => Occitan,[PL] => Polski,[PT] => Português,[RU] => Русский язык,[SL] => Slovenščina,[SR] => српски језик,[SV] => Svenska,[TR] => Türkçe,[ZH] => 中文),[installlang] => fr,[login] => ssonnet,[lodeluser] => Array ([rights] => 128,[lang] => fr,[id] => 2,[gui_complexity] => 64,[name] => ssonnet,[groups] => ,[desk] => 1,[restricted_user] => 1,[adminlodel] => 1,[admin] => 1,[editor] => 1,[redactor] => 1,[visitor] => 1,[idsession] => ,[session] => ),[clearcacheurl] => /lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr&amp;clearcache=oui,[lo] => plugins,[error] => Array (),[triggers] => Array ([0] => preview,[1] => postview,[2] => preedit,[3] => postedit,[4] => prelogin,[5] => postlogin,[6] => preauth,[7] => postauth)),[1] => Array (),[2] => Array ([0] => pdfgen,[1] => getAction))),[4] => Array ([file] => /var/www/html/lodel/lodel/scripts/controller.php,[line] => 133,[function] => _execute,[class] => Controller,[type] => ->,[args] => Array ([0] => Array ([do] => pdfgen_get,[document] => 67,[lang] => fr,[id] => 0,[idgroup] => 0,[idclass] => 0,[idparent] => 0,[idtype] => 0,[identity] => 0,[version] => 1.0,[shareurl] => /lodel/share,[extensionscripts] => php,[currenturl] => http://ara.local/lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr,[siteroot] => ,[sharedir] => .././share,[tableprefix] => ,[tp] => ,[base_rep] => Array (),[charset] => utf-8,[site] => sitenova,[db_charset] => utf8mb4,[siteinfos] => Array ([id] => 1,[title] => Site Nova,[subtitle] => ,[name] => sitenova,[path] => /sitenova,[url] => http://ara.local/lodel/sitenova,[langdef] => ,[lang] => ,[status] => 1,[upd] => 2021-10-27 14:38:13),[siteurl] => http://ara.local/lodel/sitenova,[options] => Array ([metadonneessite] => Array ([titresite] => Titresite,[soustitresite] => ,[titresiteabrege] => Titre abrégé du site,[descriptionsite] => ,[urldusite] => ,[issn] => ,[issn_electronique] => ,[editeur] => ,[adresseediteur] => ,[producteursite] => ,[diffuseursite] => ,[droitsauteur] => ,[directeurpublication] => ,[redacteurenchef] => ,[courrielwebmaster] => ,[courrielabuse] => ,[motsclesdusite] => ,[langueprincipale] => fr,[typepublication] => Revue,[pdf] => ,[pdf_electronique] => ,[imagehabillee] => ),[diffusionelectronique] => Array ([bouquetfreemium] => ,[librairieelectronique] => ,[prixcommercialisationnumero] => ),[optionsaffichage] => Array ([affichageindexannuel] => ,[affichageindexparlangue] => ,[affichageindexcr] => ,[affichageindexpersonnes] => First name Surname,[barrenavaffichagenumero] => per issue,[affichageremerciements] => top,[pub_level_accordion] => none,[firstlogo] => ,[math] => ,[hide_varia] => ),[optionsgenerales] => Array ([emversion] => 1.0.2)),[sitelang] => fr,[defaultlang] => Array ([AR] => العربية,[BS] => Bosanski jezik,[CS] => Česky,[DE] => Deutsch,[EL] => Ελληνικά,[EN] => English,[ES] => Español,[ET] => Eesti keel,[EU] => Euskara,[FA] => ‫فارسی,[FI] => Suomen kieli,[FR] => Français,[GA] => Gaeilge,[HR] => Hrvatski,[HU] => Magyar,[IT] => Italiano,[HE] => ‫עברית,[JA] => 日本語,[KV] => коми кыв,[LA] => Latine,[LV] => Latviešu valoda,[MK] => македонски јазик,[NL] => Nederlands,[OC] => Occitan,[PL] => Polski,[PT] => Português,[RU] => Русский язык,[SL] => Slovenščina,[SR] => српски језик,[SV] => Svenska,[TR] => Türkçe,[ZH] => 中文),[installlang] => fr,[login] => ssonnet,[lodeluser] => Array ([rights] => 128,[lang] => fr,[id] => 2,[gui_complexity] => 64,[name] => ssonnet,[groups] => ,[desk] => 1,[restricted_user] => 1,[adminlodel] => 1,[admin] => 1,[editor] => 1,[redactor] => 1,[visitor] => 1,[idsession] => ,[session] => ),[clearcacheurl] => /lodel/sitenova/?do=_pdfgen_get&document=67&lang=fr&amp;clearcache=oui,[lo] => plugins,[error] => Array (),[triggers] => Array ([0] => preview,[1] => postview,[2] => preedit,[3] => postedit,[4] => prelogin,[5] => postlogin,[6] => preauth,[7] => postauth)),[1] => pdfgen_getAction,[2] => plugins,[3] => Array ([0] => plugins),[4] => Array ())),[5] => Array ([file] => /var/www/html/lodel/lodel/src/index.php,[line] => 94,[function] => execute,[class] => Controller,[type] => ->,[args] => Array ([0] => Array ([0] => plugins),[1] => plugins))),[Exceptionprevious] => ))

**Comment by brrd** [comment]
J'ai verrouillé sur la version 6.
